batch:
  size: "![3+zt0zga9yw=]"
mysql:
  host: "![IFfyjr++puNHfEDCkNBkWQ==]"
  port: "![ofeowN3y6VY=]"
  username: "![bpzQi+ZzpFg=]"
  password: "![bpzQi+ZzpFg=]"
  database: "![6BKHf3c3WuqH0jfRvkKQhg==]"
  schema: "![6BKHf3c3WurkP1G+k+BZxg==]"
sqlserver:
  host: "![/7PkmYVThqxm/+4BVOVXm3J1aazBVKXMr85W3IM2BYN2c2+QsNT/og==]"
  port: "![Jvy89mn9j34=]"
  username: "![vdvLLphGdl8=]"
  password: "![EQd9K93tulUfyQFGPl1OQQ==]"
  database: "![40o1p4IbTVI=]"
  schema: "![FCb/nMuHtz4=]"
sftp:
  host: "![UM4ObEfx5NwBFrrj1kHKrMh9pE5vzUlep0GDTRWcHzE=]"
  port: "![Z1XQC24SgRI=]"
  username: "![obiKZohObQQ=]"
  password: "![joXN+nV+7WZ6a6oiT7WOMg==]"
  dir: "![LMouMDpJkgWE6ok7jlGVCcFn/XWpVjH2di0uoJz+Pas=]"