batch:
  size: '2'
mysql:
  host: '127.0.0.1'
  port: '3306'
  username: 'root'
  password: ''
  database: 'davefelcey'
sftp:
  host: 'sftp.example.com'
  port: '22'
  username: 'demo'
  password: 'xxxx'
  dir: '/home/demo/input'